INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (1, 'ANTIOQUIA', '5', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (2, 'ATLÁNTICO', '8', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (3, 'BOGOTÁ, D.C.', '11', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (4, 'BOLÍVAR', '13', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (5, 'BOYACÁ', '15', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (6, 'CALDAS', '17', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (7, 'CAQUETÁ', '18', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (8, 'CAUCA', '19', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (9, 'CESAR', '20', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (10, 'CÓRDOBA', '23', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (11, 'CUNDINAMARCA', '25', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (12, 'CHOCÓ', '27', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (13, 'HUILA', '41', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (14, 'LA GUAJIRA', '44', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (15, 'MAGDALENA', '47', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (16, 'META', '50', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (17, 'NARIÑO', '52', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (18, 'NORTE DE SANTANDER', '54', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (19, 'QUINDÍO', '63', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (20, 'RISARALDA', '66', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (21, 'SANTANDER', '68', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (22, 'SUCRE', '70', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (23, 'TOLIMA', '73', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (24, 'VALLE DEL CAUCA', '76', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (25, 'ARAUCA', '81', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (26, 'CASANARE', '85', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (27, 'PUTUMAYO', '86', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (28, 'ARCHIPIÉLAGO DE SAN ANDRÉS, PROVIDENCIA Y SANTA CATALINA', '88', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (29, 'AMAZONAS', '91', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (30, 'GUAINÍA', '94', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (31, 'GUAVIARE', '95', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (32, 'VAUPÉS', '97', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO departamentos (id, nombre, codigo_dane, created_at, updated_at) VALUES (33, 'VICHADA', '99', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
